### ISSUE TITLE
Moved repository to rantly-rb organization.

### ISSUE THREAD

**Issue by abargnesi** [rantly-rb/rantly#26]
Hey everybody. Due to the group of contributors so far it is time to create a rantly github organization. The [abargnesi/rantly](https://github.com/abargnesi/rantly) repository now redirects to [rantly-rb/rantly](https://github.com/rantly-rb/rantly). Valuable work shouldn't be held up by one person when there is an active group of contributors.

Would anyone like to be added to the organization as a contributor?

**Comment by Ana06** [comment]
@abargnesi 

> Hey everybody. Due to the group of contributors so far it is time to create a rantly github organization. The abargnesi/rantly repository now redirects to rantly-rb/rantly. Valuable work shouldn't be held up by one person when there is an active group of contributors.

Great idea! :+1: But the project style appear to be a fork from _hayeah/rantly_. Couldn't we avoid that? It is quite annoying as when sending PR Github interprets that you want to send them to _hayeah/rantly_. I saw other moved projects were this doesn't happens.


> Would anyone like to be added to the organization as a contributor?

Yes! :wink:

**Comment by dennyabraham** [comment]
You might have to re-fork from rantly-rb now that it's moved. I rebuilt my fork for some work I'm doing later and it uses rantly-rb as the base.

I would also like to be added as a contributor.

**Comment by abargnesi** [comment]
Oh man I dropped this one. Just reached out to GitHub support to change modes.

**Comment by abargnesi** [comment]
You were both added as contributors with write permissions on all rantly-rb repositories.

cc @Ana06, @dennyabraham

**Comment by abargnesi** [comment]
Github changed the mode to normal. All forks of this repository remain attached.
