### ISSUE TITLE
Range for floats?

### ISSUE THREAD

**Issue by Stratus3D** [rantly-rb/rantly#60]
I've been using the `range` method to select integers within a specified range, and I see there is a `float` method that returns a random float, but I need a random float within a specified range. Something like:

```
range_float(23.4, 56.7) 
# => 34.56
```

Is this something that exists in Rantly? And if not would a contribution to add this method be welcome? Or is there a better way of doing this outside of Rantly?

**Comment by Stratus3D** [comment]
I'm using https://stackoverflow.com/a/1711720/1245380 for now.

It looks like I could update the existing `range` method to handle floats as well as strings, and implicitly generate the right type of range. Adding a new `range_float` method should also be easy too.

**Comment by Ana06** [comment]
I would say there is a bug:

```ruby
Rantly { range(23.4, 56.7) } #=> 54.4
Rantly { range(23.4, 56) } #=> 29.4
Rantly { range(3, 28.9) } #=> 27
Rantly { range(3.0, 28.9) } #=> 25.0
```
