### ISSUE TITLE
Using rantly with rspec-rails

### ISSUE THREAD

**Issue by diasbruno** [rantly-rb/rantly#78]
Hi,

I'm not sure if there is a problem with my project's setup (rails app), but when I try to use 
this package I got an error like `cannot find -- rspec`.

It seems that `rspec-rails` is its own project (use the base package like rspec-core, 
rspec-expectations and so on...).

By changing the rspec package to the rspec-rails everything works (see [diasbruno/rantly#17111a38e8e98c97230ecf32454f0d666918ef77](https://github.com/diasbruno/rantly/commit/17111a38e8e98c97230ecf32454f0d666918ef77))

So, I don't know if this package should also provide an extension for this case: `rspec_rails_extensions.rb`.

**Comment by bbugh** [comment]
You can work around this by explicitly including `rspec` in your `Gemfile`, along with `rspec-rails`.

```ruby
gem 'rspec'
gem 'rspec-rails'
```

**Comment by diasbruno** [comment]
Thanks, @bbugh. I'll give it a try.

**Comment by diasbruno** [comment]
I'm not sure if It would be a good idea since `rspec` e `rspec-rails`, they both use the same rspec "core" libraries, but they are 2 "different" projects...so, it should not be necessary to include rspec as a dependency - I think...

Maybe rantly could provide a specific extension for rspec-rails as `rspec_rails_extensions.rb`, so we don't need to add extra dependencies.
